services:
  - type: web
    name: ai-video-generator
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
      - key: HF_TOKEN
        sync: false  # Set this manually in Render dashboard
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: ai-video-storage
      mountPath: /app/static
      sizeGB: 1